### ISSUE TITLE
atl_res_patch requires id, not necessary when attempting to make res patches for 1 ind

### ISSUE THREAD

**Issue by CBeardsworth** [pratikunterwegs/atlastools#28]
I was trying to make a residence patch for just one individual. The function requires information I haven't got in the df and that isn't in the help file.

**Comment by CBeardsworth** [comment]
Perhaps this should be a warning rather than an error.

**Comment by pratikunterwegs** [comment]
This is a requirement, unfortunately. I can explain how it emerged.

In multiple places in `atl_res_patch` there are summary procedures on `data.table`s.
In these, any column not specified as a grouping column is lost.

Typically, when dealing with many tags, one would like to combine the various residence patch summary data.tables into one big data.table, which can be saved to file.
In this workflow, the `id` column is necessary to distinguish different individuals. Hence `id` needs to come out of the residence patch function as a valid column. Hence the error, since `id` is a required grouping column.

In fact, in `watlastools` another column `tide_number` is also required, because one wants that info too when dealing with a large dataset of residence patches.

I would suggest assigning a working identity column to the data, called `id` but containing a value that makes it clear that it is not really an identity, such as "test", or whatever.

I can also add this requirement to the documentation.

**Comment by CBeardsworth** [comment]
The MS says : A cleaned movement track can be classified into residence patches using the function atl_res_patch (see Figure 8.a).atl_res_patch requires only three parameters: (1) the distance threshold between positions (calledbuffersize), (2) the distance threshold between clusters of positions (calledlimspatindep), and (3) the time interval between clusters (calledlimtimeindep). 

From this it looks like no other columns are necessary. Perhaps we could have a grouping argument in the function? if T then it runs as it did before but if F then we should be able to run residence patches on 1 individual, without tide or any grouping factor. I would assume that residence patches should be able to also find the roost sites and it is the user who can determine the biological function of the site from this.

**Comment by pratikunterwegs** [comment]
I think this is best addressed in the documentation of the function, but I could add a line in the m/s "the function also expects an id column". This is normal (see `adehabitat*` and `recurse`).

Adding a group argument to the `atlastools` function would tempt users to rely on the function for essentially splitting their data into meaningful subsets.

While valid, what I'd prefer for them to do is to `split` their data into a list-like object, and apply the function to each list element.
The difference is that the second method forces them to think about whether to split data into subsets at all, and if yes, to acknowledge it explicitly (and justify it!).

Does that make sense?

> I would assume that residence patches should be able to also find the roost sites and it is the user who can determine the biological function of the site from this.

I didn't understand this last bit, sorry. 
The method will indeed find roost sites as residence patches, no inference is made about this.

**Comment by CBeardsworth** [comment]
I didn't mean for the function to group the data for users, just enable the lack of grouping to be an option. Perhaps an argument that denotes the group column like group = "id" which could also be set to group = NA? I was surprised to have to add a column of the same repeated value. This seems like an unnecessary step but I can see it could be solved through the documentation.

**Comment by pratikunterwegs** [comment]
Ah, you mean to dump the `id` column entirely in the process? 
So the residence patches would come out with the columns `patch, x_median, y_median ...`.

That's possible --- but then users might complain their `id`s are lost.
The time costs are of adding a 'fake' id _vs_ re-doing the analysis (on large datasets) because the patches can't be linked to individuals.

To be safe, I'll keep it in for now, and if lots more folks ask for it to go, we can revisit the issue?
